name: 'Truncate String'
description: 'Simple truncate string'
author: "Brian Kurtz"
branding:
  icon: briefcase
  color: orange
inputs:
  stringToTruncate:
    description: String to be truncated
    required: true
  maxLength:
    description: Max length of the string
    required: true
  removeDanglingCharacters:
    description: Remove any of the provided dangling characters. No seperation between characters e.g. -,!%
    default: ''
  truncationSymbol:
    description: Appends a string to the end of the truncated string to indicate truncation has occurred
outputs:
  string:
    description: The truncated string
runs:
  using: 'node20'
  main: 'dist/index.js'
